import test from 'node:test';
import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';

test('exact PostgreSQL migration RLS with Auth and Storage function stubs, not Supabase Cloud E2E', async () => {
const db = await PGlite.create();
const owner = '11111111-1111-4111-8111-111111111111';
const donor = '22222222-2222-4222-8222-222222222222';
const cover = '33333333-3333-4333-8333-333333333333';
const unused = '44444444-4444-4444-8444-444444444444';
const cause = '55555555-5555-4555-8555-555555555555';
await db.exec(`
  create role anon nologin; create role authenticated nologin; create role service_role nologin bypassrls;
  create schema auth; create schema storage;
  create table auth.users(id uuid primary key);
  create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid$$;
  create function auth.jwt() returns jsonb language sql stable as $$select jsonb_build_object('is_anonymous', coalesce(nullif(current_setting('request.jwt.claim.is_anonymous', true),''),'false')::boolean)$$;
  create function storage.foldername(name text) returns text[] language sql immutable as $$select (string_to_array(name,'/'))[1:array_length(string_to_array(name,'/'),1)-1]$$;
  create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
  create table storage.objects(id uuid primary key,bucket_id text,name text);
  alter table storage.objects enable row level security;
  grant usage on schema public,auth,storage to anon,authenticated,service_role;
  grant select,insert,delete on storage.objects to anon,authenticated,service_role;
  insert into auth.users values ('${owner}'),('${donor}');
`);
const migration = await readFile(new URL('../supabase/migrations/20261006071201_circle_workspace.sql', import.meta.url),'utf8');
await db.exec(migration);
const role = async (name: string, uid='') => { await db.exec(`reset role; set role ${name}`); await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[uid]); };
await role('authenticated',owner);
await db.query(`insert into public.circle_workspace_media(id,owner_id,object_path,name,mime,size,sha256) values ($1,$2,$3,'cover.webp','image/webp',100,$4)`, [cover,owner,`${owner}/${cover}.webp`,'a'.repeat(64)]);
await db.query(`insert into public.circle_workspace_media(id,owner_id,object_path,name,mime,size,sha256) values ($1,$2,$3,'unused.webp','image/webp',100,$4)`, [unused,owner,`${owner}/${unused}.webp`,'b'.repeat(64)]);
await db.query(`insert into storage.objects(id,bucket_id,name) values ($1,'circle-workspace-media',$2),($3,'circle-workspace-media',$4)`, [cover,`${owner}/${cover}.webp`,unused,`${owner}/${unused}.webp`]);
await role('anon');
assert.equal((await db.query('select * from public.circle_workspace_media')).rows.length,0);
assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await role('authenticated',owner);
await db.query(`insert into public.circle_workspace_campaigns(id,organizer_id,organizer_name,title,story,location,category,goal_php,allowance_pct,cover_media_id) values ($1,$2,'Organizer test','Bantu shelter kucing','Cerita campaign cukup panjang agar lulus validasi SQL dan RLS.','Jakarta','animals',1000,5,$3)`, [cause,owner,cover]);
await role('anon');
assert.equal((await db.query('select * from public.circle_workspace_campaigns')).rows.length,1);
assert.equal((await db.query('select * from public.circle_workspace_media')).rows.length,1);
assert.equal((await db.query('select * from storage.objects')).rows.length,1);
await role('authenticated',donor);
await db.query(`select set_config('request.jwt.claim.is_anonymous','true',false)`);
await assert.rejects(db.query(`insert into public.circle_workspace_follows(campaign_id,user_id) values($1,$2)`,[cause,donor]));
await db.query(`select set_config('request.jwt.claim.is_anonymous','false',false)`);
await assert.rejects(db.query(`update public.circle_workspace_campaigns set allowance_pct=10 where id=$1`,[cause]));
await assert.rejects(db.query(`insert into public.circle_workspace_updates(id,campaign_id,organizer_id,title,body,kind,media_ids) values ('66666666-6666-4666-8666-666666666666',$1,$2,'Spoofed update','Tidak boleh jadi update organizer','delivery',array[$3::uuid])`,[cause,donor,cover]));
await assert.rejects(db.query(`insert into public.circle_workspace_reviews(id,campaign_id,organizer_id,donor_id,donor_name,stars,comment) values ('77777777-7777-4777-8777-777777777777',$1,$2,$3,'Donor',5,'Review tidak boleh dipalsukan')`,[cause,owner,donor]));
await db.query(`insert into public.circle_workspace_follows(campaign_id,user_id) values($1,$2)`,[cause,donor]);
assert.equal((await db.query('select * from public.circle_workspace_follows')).rows.length,1);
await role('authenticated',owner);
assert.equal((await db.query('select * from public.circle_workspace_follows')).rows.length,0);
await db.query(`insert into public.circle_workspace_updates(id,campaign_id,organizer_id,title,body,kind,media_ids) values ('66666666-6666-4666-8666-666666666666',$1,$2,'Bukti penyaluran','Bantuan sampai ke shelter dan kebutuhan terpenuhi','delivery',array[$3::uuid])`,[cause,owner,cover]);
await role('service_role');
await db.query(`update public.circle_workspace_campaigns set status='completed' where id=$1`,[cause]);
await db.query(`insert into public.circle_workspace_reviews(id,campaign_id,organizer_id,donor_id,donor_name,stars,comment) values ('77777777-7777-4777-8777-777777777777',$1,$2,$3,'Donor',5,'Review hanya setelah server verifikasi chain')`,[cause,owner,donor]);
await assert.rejects(db.query(`insert into public.circle_workspace_reviews(id,campaign_id,organizer_id,donor_id,donor_name,stars,comment) values ('88888888-8888-4888-8888-888888888888',$1,$2,$3,'Donor',5,'Review duplikat harus ditolak')`,[cause,owner,donor]));
await role('authenticated',owner);
await assert.rejects(db.query(`insert into public.circle_workspace_updates(id,campaign_id,organizer_id,title,body,kind) values ('99999999-9999-4999-8999-999999999999',$1,$2,'Setelah selesai','Update setelah selesai harus ditolak','progress')`,[cause,owner]));
console.log('PASS: exact migration compiles in PostgreSQL WASM; private/unpublished vs public media, owner updates, immutable campaign terms, donor follows, server-only reviews, uniqueness, completion gates enforced. This is not a Supabase Cloud/Auth/Storage end-to-end test.');
await db.close();
});
