import type { Locale } from "./config";

const en = {
  title: "Campaign photos", region: "Campaign photo gallery", previous: "Previous photo", next: "Next photo", photo: "Campaign photo", thumbnail: "Show photo",
  publicLabel: "Organizer photos · not independently verified", demoLabel: "AI illustration · local example",
  publicHint: "Photos published by the organizer are public and unverified. They are not delivery proof or a wallet approval.",
  demoHint: "Illustrative AI photos for this local example, not a real campaign or proof of delivery.",
  empty: "This campaign has no organizer photos yet.", missing: "This photo could not be loaded.", loading: "Loading campaign photos…", retry: "Retry",
  editor: "Publish campaign photos", choose: "Choose 3–6 photos", hint: "Select 3–6 distinct, still JPEG, PNG or WebP photos, each up to 12 MB before resizing. The gallery will be replaced. Images are resized and location metadata is removed.",
  consent: "I have permission to publish these photos publicly. I will not include sensitive information or photos without consent.",
  preparing: "Preparing photos…", saving: "Publishing photos…", saved: "Campaign photos published.", selected: "Selected photos", localOnly: "Photo publishing is unavailable in local preview. Example photos are not organizer uploads.",
  invalid_count: "Choose between 3 and 6 photos before publishing.", invalid_type: "Choose only JPEG, PNG or WebP photos.", too_large: "An image is too large to process safely. Choose a smaller photo.", duplicate_photos: "Choose distinct photos. Duplicate image content is not allowed.", invalid_image: "An image is invalid or animated. Choose valid, still photos.", unsupported: "This browser cannot prepare photos. Try an up-to-date browser.", preparation_failed: "A photo could not be compressed safely. Choose a smaller photo.",
  invalid_campaign: "This campaign is not available.", local_preview: "Photo publishing is unavailable in local preview.", not_configured: "Campaign photo storage is not configured. No photos have been published.", unavailable: "Campaign photos are temporarily unavailable. Try again.", unauthenticated: "Sign in as the organizer to publish campaign photos.", account_changed: "Your account changed. Reload before publishing photos.", no_wallet: "Your account has no managed wallet. Photo publishing is unavailable.", not_creator: "Only the campaign creator can publish these photos.", invalid_photos: "Choose 3–6 distinct, valid photos within the upload limits.", ack_required: "Confirm public photo publication before continuing.", save_failed: "Publication could not be confirmed. Reload to check the gallery before trying again.",
};
type GalleryCopy = typeof en;
const copies: Record<Locale, GalleryCopy> = {
  en,
  id: {
    title: "Foto campaign", region: "Galeri foto campaign", previous: "Foto sebelumnya", next: "Foto berikutnya", photo: "Foto campaign", thumbnail: "Tampilkan foto",
    publicLabel: "Foto organizer · belum diverifikasi independen", demoLabel: "Ilustrasi AI · contoh lokal",
    publicHint: "Foto yang dipublikasikan organizer bersifat publik dan belum diverifikasi. Foto ini bukan bukti penyaluran atau persetujuan wallet.",
    demoHint: "Ilustrasi AI untuk contoh lokal, bukan campaign nyata atau bukti penyaluran.",
    empty: "Campaign ini belum memiliki foto dari organizer.", missing: "Foto ini tidak dapat dimuat.", loading: "Memuat foto campaign…", retry: "Coba lagi",
    editor: "Publikasikan foto campaign", choose: "Pilih 3–6 foto", hint: "Pilih 3–6 foto JPEG, PNG atau WebP berbeda dan tidak bergerak, masing-masing maksimal 12 MB sebelum penyesuaian. Galeri akan diganti. Ukuran foto disesuaikan dan metadata lokasi dihapus.",
    consent: "Saya memiliki izin untuk mempublikasikan foto ini. Saya tidak akan menyertakan informasi sensitif atau foto tanpa persetujuan.",
    preparing: "Menyiapkan foto…", saving: "Mempublikasikan foto…", saved: "Foto campaign telah dipublikasikan.", selected: "Foto dipilih", localOnly: "Publikasi foto tidak tersedia dalam preview lokal. Foto contoh bukan upload dari organizer.",
    invalid_count: "Pilih 3 sampai 6 foto sebelum mempublikasikan.", invalid_type: "Pilih hanya foto JPEG, PNG atau WebP.", too_large: "Ukuran gambar terlalu besar untuk diproses dengan aman. Pilih foto lebih kecil.", duplicate_photos: "Pilih foto berbeda. Gambar dengan isi yang sama tidak diperbolehkan.", invalid_image: "Gambar tidak valid atau bergerak. Pilih foto valid yang tidak bergerak.", unsupported: "Browser ini tidak dapat menyiapkan foto. Coba browser versi terbaru.", preparation_failed: "Foto tidak dapat dikompres dengan aman. Pilih foto lebih kecil.",
    invalid_campaign: "Campaign ini tidak tersedia.", local_preview: "Publikasi foto tidak tersedia dalam preview lokal.", not_configured: "Penyimpanan foto campaign belum dikonfigurasi. Belum ada foto yang dipublikasikan.", unavailable: "Foto campaign sementara tidak tersedia. Coba lagi.", unauthenticated: "Masuk sebagai organizer untuk mempublikasikan foto campaign.", account_changed: "Akun Anda berubah. Muat ulang sebelum mempublikasikan foto.", no_wallet: "Akun Anda belum memiliki wallet terkelola. Publikasi foto tidak tersedia.", not_creator: "Hanya pembuat campaign yang dapat mempublikasikan foto ini.", invalid_photos: "Pilih 3–6 foto berbeda yang valid dan sesuai batas upload.", ack_required: "Setujui publikasi foto sebelum melanjutkan.", save_failed: "Publikasi belum dapat dikonfirmasi. Muat ulang untuk memeriksa galeri sebelum mencoba lagi.",
  },
  tl: {
    title: "Mga larawan ng campaign", region: "Gallery ng campaign", previous: "Nakaraang larawan", next: "Susunod na larawan", photo: "Larawan ng campaign", thumbnail: "Ipakita ang larawan",
    publicLabel: "Larawan ng organizer · hindi pa beripikado", demoLabel: "Ilustrasyong AI · lokal na halimbawa",
    publicHint: "Pampubliko at hindi beripikado ang mga larawan ng organizer. Hindi ito patunay ng pamamahagi o pag-apruba ng wallet.", demoHint: "Mga ilustrasyong AI para sa lokal na halimbawa, hindi tunay na campaign o patunay ng pamamahagi.",
    empty: "Wala pang larawan mula sa organizer ang campaign na ito.", missing: "Hindi ma-load ang larawang ito.", loading: "Nilo-load ang mga larawan…", retry: "Subukan muli",
    editor: "Ilathala ang mga larawan", choose: "Pumili ng 3–6 na larawan", hint: "Pumili ng 3–6 magkakaibang JPEG, PNG o WebP na hindi gumagalaw, hanggang 12 MB bawat isa bago baguhin ang laki. Papalitan ang gallery. Binabago ang laki at inaalis ang metadata ng lokasyon.",
    consent: "May pahintulot akong ilathala ang mga larawang ito. Hindi ako magsasama ng sensitibong impormasyon o larawang walang pahintulot.", preparing: "Inihahanda ang mga larawan…", saving: "Inilalathala ang mga larawan…", saved: "Nailathala ang mga larawan ng campaign.", selected: "Napiling mga larawan", localOnly: "Hindi available ang paglalathala sa lokal na preview. Hindi upload ng organizer ang mga halimbawang larawan.",
    invalid_count: "Pumili ng 3 hanggang 6 na larawan bago ilathala.", invalid_type: "JPEG, PNG o WebP na larawan lamang ang piliin.", too_large: "Masyadong malaki ang larawan para ligtas na iproseso. Pumili ng mas maliit.", duplicate_photos: "Pumili ng magkakaibang larawan. Hindi pinapayagan ang magkaparehong nilalaman.", invalid_image: "Hindi wasto o gumagalaw ang larawan. Pumili ng wastong still photo.", unsupported: "Hindi makapaghanda ng larawan ang browser. Gumamit ng bagong bersyon.", preparation_failed: "Hindi ligtas na ma-compress ang larawan. Pumili ng mas maliit.",
    invalid_campaign: "Hindi available ang campaign.", local_preview: "Hindi available ang paglalathala sa lokal na preview.", not_configured: "Hindi pa naka-configure ang storage. Walang nailathalang larawan.", unavailable: "Pansamantalang hindi available ang mga larawan. Subukan muli.", unauthenticated: "Mag-sign in bilang organizer para maglathala ng mga larawan.", account_changed: "Nagbago ang account. I-reload bago maglathala.", no_wallet: "Walang managed wallet ang account. Hindi available ang paglalathala.", not_creator: "Ang gumawa lamang ng campaign ang maaaring maglathala.", invalid_photos: "Pumili ng 3–6 magkakaibang wastong larawan sa limitasyon ng upload.", ack_required: "Kumpirmahin ang pampublikong paglalathala bago magpatuloy.", save_failed: "Hindi makumpirma ang paglalathala. I-reload para suriin ang gallery bago subukan muli.",
  },
  vi: {
    title: "Ảnh chiến dịch", region: "Thư viện ảnh chiến dịch", previous: "Ảnh trước", next: "Ảnh tiếp theo", photo: "Ảnh chiến dịch", thumbnail: "Hiện ảnh",
    publicLabel: "Ảnh nhà tổ chức · chưa được xác minh độc lập", demoLabel: "Minh họa AI · ví dụ cục bộ",
    publicHint: "Ảnh do nhà tổ chức đăng là công khai và chưa được xác minh. Đây không phải bằng chứng phân phối hay phê duyệt của ví.", demoHint: "Ảnh minh họa AI cho ví dụ cục bộ, không phải chiến dịch thật hoặc bằng chứng phân phối.",
    empty: "Chiến dịch này chưa có ảnh từ nhà tổ chức.", missing: "Không thể tải ảnh này.", loading: "Đang tải ảnh chiến dịch…", retry: "Thử lại",
    editor: "Đăng ảnh chiến dịch", choose: "Chọn 3–6 ảnh", hint: "Chọn 3–6 ảnh JPEG, PNG hoặc WebP khác nhau, không động, mỗi ảnh tối đa 12 MB trước khi đổi kích thước. Thư viện sẽ được thay thế. Kích thước được điều chỉnh và siêu dữ liệu vị trí bị xóa.",
    consent: "Tôi được phép đăng công khai các ảnh này. Tôi sẽ không đăng thông tin nhạy cảm hoặc ảnh chưa được đồng ý.", preparing: "Đang chuẩn bị ảnh…", saving: "Đang đăng ảnh…", saved: "Đã đăng ảnh chiến dịch.", selected: "Ảnh đã chọn", localOnly: "Không thể đăng ảnh trong bản xem trước cục bộ. Ảnh ví dụ không phải ảnh do nhà tổ chức tải lên.",
    invalid_count: "Chọn từ 3 đến 6 ảnh trước khi đăng.", invalid_type: "Chỉ chọn ảnh JPEG, PNG hoặc WebP.", too_large: "Ảnh quá lớn để xử lý an toàn. Chọn ảnh nhỏ hơn.", duplicate_photos: "Chọn các ảnh khác nhau. Không cho phép nội dung ảnh trùng lặp.", invalid_image: "Ảnh không hợp lệ hoặc động. Chọn ảnh tĩnh hợp lệ.", unsupported: "Trình duyệt không thể chuẩn bị ảnh. Thử trình duyệt mới nhất.", preparation_failed: "Không thể nén ảnh an toàn. Chọn ảnh nhỏ hơn.",
    invalid_campaign: "Chiến dịch không khả dụng.", local_preview: "Không thể đăng ảnh trong bản xem trước cục bộ.", not_configured: "Bộ nhớ ảnh chưa được cấu hình. Chưa có ảnh nào được đăng.", unavailable: "Ảnh chiến dịch tạm thời không khả dụng. Thử lại.", unauthenticated: "Đăng nhập với tư cách nhà tổ chức để đăng ảnh.", account_changed: "Tài khoản đã thay đổi. Tải lại trước khi đăng ảnh.", no_wallet: "Tài khoản chưa có ví được quản lý. Không thể đăng ảnh.", not_creator: "Chỉ người tạo chiến dịch mới có thể đăng ảnh.", invalid_photos: "Chọn 3–6 ảnh khác nhau, hợp lệ và trong giới hạn tải lên.", ack_required: "Xác nhận đăng ảnh công khai trước khi tiếp tục.", save_failed: "Chưa xác nhận được việc đăng ảnh. Tải lại để kiểm tra thư viện trước khi thử lại.",
  },
};
export function campaignGalleryCopy(locale: Locale) { return copies[locale] ?? en; }
