import type { Locale } from "./config";

const en = {
  step: "FINISH YOUR ACCOUNT", title: "Choose your @username", intro: "A username is required to use your Salapi account. People can find you and send by name.",
  label: "Your username", hint: "3-32 letters, numbers or underscores. Your username is public and unique.", claim: "Save username", saving: "Confirming your username…", checking: "Checking your account…",
  unavailable: "We could not verify your username. Your existing name has not been changed.", retry: "Check again", invalid: "Use 3-32 letters, numbers or underscores.",
  taken: "That username is already taken. Choose another.", failed: "The username was not saved. Please try again.", pending: "The result is still being checked. Do not submit again yet.",
  wallet: "Prepare your personal Testnet wallet before choosing a username.", setup: "Continue wallet setup", switchAccount: "Use another account", testnet: "Saved on Stellar Testnet. Network fees may apply. No tokens are sent to another user.",
  preview: "Local example only. This does not register a username or submit a transaction.",
};
const copies = {
  en,
  id: { step: "LENGKAPI AKUNMU", title: "Pilih @username kamu", intro: "Username wajib untuk memakai akun Salapi. Orang lain bisa menemukanmu dan mengirim lewat nama.", label: "Username kamu", hint: "3-32 huruf, angka, atau garis bawah. Username bersifat publik dan unik.", claim: "Simpan username", saving: "Mengonfirmasi username…", checking: "Memeriksa akunmu…", unavailable: "Username belum bisa diverifikasi. Nama yang sudah ada tidak diubah.", retry: "Periksa lagi", invalid: "Gunakan 3-32 huruf, angka, atau garis bawah.", taken: "Username ini sudah dipakai. Pilih yang lain.", failed: "Username belum tersimpan. Coba lagi.", pending: "Hasil masih diperiksa. Jangan kirim ulang dulu.", wallet: "Siapkan wallet Testnet pribadi sebelum memilih username.", setup: "Lanjutkan penyiapan wallet", switchAccount: "Gunakan akun lain", testnet: "Disimpan di Stellar Testnet. Biaya jaringan dapat berlaku. Tidak ada token yang dikirim ke pengguna lain.", preview: "Contoh lokal saja. Tidak mendaftarkan username atau mengirim transaksi." },
  tl: { step: "KUMPLETUHIN ANG ACCOUNT", title: "Piliin ang iyong @username", intro: "Kailangan ng username para gamitin ang Salapi account. Mahahanap ka at mapapadalhan gamit ang pangalan.", label: "Iyong username", hint: "3-32 letra, numero o underscore. Pampubliko at natatangi ang username.", claim: "I-save ang username", saving: "Kinukumpirma ang username…", checking: "Sinusuri ang account…", unavailable: "Hindi ma-verify ang username. Hindi nabago ang dati mong pangalan.", retry: "Suriin muli", invalid: "Gumamit ng 3-32 letra, numero o underscore.", taken: "Ginagamit na ang username. Pumili ng iba.", failed: "Hindi na-save ang username. Subukan muli.", pending: "Sinusuri pa ang resulta. Huwag munang magsumite muli.", wallet: "Ihanda ang personal na Testnet wallet bago pumili ng username.", setup: "Ituloy ang wallet setup", switchAccount: "Gumamit ng ibang account", testnet: "Naka-save sa Stellar Testnet. Maaaring may network fee. Walang token na ipapadala sa ibang user.", preview: "Lokal na halimbawa lamang. Walang username registration o transaksyon." },
  vi: { step: "HOÀN TẤT TÀI KHOẢN", title: "Chọn @username của bạn", intro: "Cần có tên người dùng để dùng tài khoản Salapi. Người khác có thể tìm và gửi bằng tên.", label: "Tên người dùng", hint: "3-32 chữ cái, chữ số hoặc dấu gạch dưới. Tên công khai và duy nhất.", claim: "Lưu tên người dùng", saving: "Đang xác nhận tên…", checking: "Đang kiểm tra tài khoản…", unavailable: "Chưa xác minh được tên người dùng. Tên hiện có không bị thay đổi.", retry: "Kiểm tra lại", invalid: "Dùng 3-32 chữ cái, chữ số hoặc dấu gạch dưới.", taken: "Tên này đã được dùng. Hãy chọn tên khác.", failed: "Chưa lưu được tên. Hãy thử lại.", pending: "Đang kiểm tra kết quả. Chưa gửi lại yêu cầu.", wallet: "Chuẩn bị ví Testnet cá nhân trước khi chọn tên.", setup: "Tiếp tục thiết lập ví", switchAccount: "Dùng tài khoản khác", testnet: "Lưu trên Stellar Testnet. Có thể có phí mạng. Không gửi token cho người dùng khác.", preview: "Chỉ là ví dụ cục bộ. Không đăng ký tên hoặc gửi giao dịch." },
} satisfies Record<Locale, Record<keyof typeof en, string>>;
const verificationCopies = {
  en: { verifyStep: "ACCOUNT STATUS", verifyTitle: "Check your account", verifyIntro: "We need to verify your account before continuing. This does not mean you need a new username." },
  id: { verifyStep: "STATUS AKUN", verifyTitle: "Periksa akunmu", verifyIntro: "Akunmu perlu diverifikasi sebelum melanjutkan. Ini bukan berarti kamu perlu membuat username baru." },
  tl: { verifyStep: "STATUS NG ACCOUNT", verifyTitle: "Suriin ang iyong account", verifyIntro: "Kailangang ma-verify ang account bago magpatuloy. Hindi ito nangangahulugang kailangan ng bagong username." },
  vi: { verifyStep: "TRẠNG THÁI TÀI KHOẢN", verifyTitle: "Kiểm tra tài khoản", verifyIntro: "Cần xác minh tài khoản trước khi tiếp tục. Điều này không có nghĩa là bạn cần tạo tên người dùng mới." },
} satisfies Record<Locale, { verifyStep: string; verifyTitle: string; verifyIntro: string }>;
const allCopies = {
  en: { ...copies.en, ...verificationCopies.en }, id: { ...copies.id, ...verificationCopies.id },
  tl: { ...copies.tl, ...verificationCopies.tl }, vi: { ...copies.vi, ...verificationCopies.vi },
};
export function usernameOnboardingCopy(locale: Locale) { return allCopies[locale]; }
